/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senac.adega.telas;

/**
 *
 * @author Dani
 */
public class Vendas extends javax.swing.JFrame {

    /**
     * Creates new form Vendas
     */
    public Vendas() {
        initComponents();
        
        // centralizar
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoFormaPagamento = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelPedido = new javax.swing.JPanel();
        lblCódigoTelaPedido = new javax.swing.JLabel();
        txtCódigoTelaPedido = new javax.swing.JTextField();
        btnRemoverTelaPedido = new javax.swing.JButton();
        lblSubtotalTelaPedido = new javax.swing.JLabel();
        btnAdicionarTelaPedido = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTelaPedido = new javax.swing.JTable();
        lblProdutoTelaPedido = new javax.swing.JLabel();
        txtProdutoTelaPedido = new javax.swing.JTextField();
        txtSubtotalTelaPedido = new javax.swing.JTextField();
        lblQuantidadeTelaPedido = new javax.swing.JLabel();
        txtQuantidadeTelaPedido = new javax.swing.JTextField();
        btnAvançarTelaPedido = new javax.swing.JButton();
        lblCódigoDescontoTelaPedido = new javax.swing.JLabel();
        txtCódigoDescontoTelaPedido = new javax.swing.JTextField();
        PanelConfirmPedido = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTelaConfirmPedido = new javax.swing.JTable();
        btnAvançarTelaConfirmaçãoPedido = new javax.swing.JButton();
        lblTotalPagarTelaConfirmPedido = new javax.swing.JLabel();
        txtlTotalPagarTelaConfirmPedido = new javax.swing.JTextField();
        btnVoltarTelaConfirmaçãoPedido = new javax.swing.JButton();
        PanelFormaPagamento = new javax.swing.JPanel();
        lblEscolhaFormaPagamento = new javax.swing.JLabel();
        radioBtnDinheiro = new javax.swing.JRadioButton();
        radioBtnCartãoDébito = new javax.swing.JRadioButton();
        radioBtnCartãoCrédito = new javax.swing.JRadioButton();
        radioBtnTicketRefeição = new javax.swing.JRadioButton();
        lblSubtotalTelaFormaPagamento = new javax.swing.JLabel();
        lblTotalRecebidoTelaFormaPagamento = new javax.swing.JLabel();
        lblTrocoTelaFormaPagamento = new javax.swing.JLabel();
        txtSubtotalTelaFormaPagamento = new javax.swing.JTextField();
        txtTotalRecebidoFormaPag = new javax.swing.JTextField();
        txtTrocoTelaFormaPagamento = new javax.swing.JTextField();
        btnAvançarTelaFormaPagamento = new javax.swing.JButton();
        btnVoltarTelaFormaPagamento = new javax.swing.JButton();
        PanelFinalizarPedido = new javax.swing.JPanel();
        lblClienteTelaFinalizarPedido = new javax.swing.JLabel();
        lblCodPedidoTelaFinalizarPedido = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableTelaFinalizarPedido = new javax.swing.JTable();
        txtClienteTelaFinalizarPedido = new javax.swing.JTextField();
        txtCodPedidoTelaFinalizarPedido = new javax.swing.JTextField();
        btnFinalizar = new javax.swing.JButton();
        btnVoltarTelaFinalizarPedido = new javax.swing.JButton();
        lblÁreaVendas = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Vendas");

        lblCódigoTelaPedido.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCódigoTelaPedido.setText("Código");

        btnRemoverTelaPedido.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnRemoverTelaPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/-.png"))); // NOI18N
        btnRemoverTelaPedido.setText("Remover");
        btnRemoverTelaPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverTelaPedidoActionPerformed(evt);
            }
        });

        lblSubtotalTelaPedido.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblSubtotalTelaPedido.setText("Subtotal ");

        btnAdicionarTelaPedido.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnAdicionarTelaPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/+.png"))); // NOI18N
        btnAdicionarTelaPedido.setText("Adicionar");

        tableTelaPedido.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tableTelaPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produtos", "Quantidade", "Preço"
            }
        ));
        jScrollPane1.setViewportView(tableTelaPedido);

        lblProdutoTelaPedido.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblProdutoTelaPedido.setText("Produto");

        lblQuantidadeTelaPedido.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblQuantidadeTelaPedido.setText("Quantidade");

        btnAvançarTelaPedido.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnAvançarTelaPedido.setText("Avançar >>");

        lblCódigoDescontoTelaPedido.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lblCódigoDescontoTelaPedido.setText("Código de Desconto");

        javax.swing.GroupLayout PanelPedidoLayout = new javax.swing.GroupLayout(PanelPedido);
        PanelPedido.setLayout(PanelPedidoLayout);
        PanelPedidoLayout.setHorizontalGroup(
            PanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPedidoLayout.createSequentialGroup()
                        .addGroup(PanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                            .addGroup(PanelPedidoLayout.createSequentialGroup()
                                .addComponent(lblSubtotalTelaPedido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSubtotalTelaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(lblCódigoDescontoTelaPedido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCódigoDescontoTelaPedido)))
                        .addContainerGap())
                    .addGroup(PanelPedidoLayout.createSequentialGroup()
                        .addGroup(PanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdicionarTelaPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCódigoTelaPedido)
                            .addComponent(txtCódigoTelaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(PanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRemoverTelaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProdutoTelaPedido)
                            .addComponent(txtProdutoTelaPedido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblQuantidadeTelaPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtQuantidadeTelaPedido))
                        .addGap(48, 48, 48))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPedidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAvançarTelaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanelPedidoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdicionarTelaPedido, btnRemoverTelaPedido});

        PanelPedidoLayout.setVerticalGroup(
            PanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCódigoTelaPedido)
                    .addComponent(lblProdutoTelaPedido)
                    .addComponent(lblQuantidadeTelaPedido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCódigoTelaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelPedidoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(PanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProdutoTelaPedido)
                            .addComponent(txtQuantidadeTelaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(PanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarTelaPedido)
                    .addComponent(btnRemoverTelaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSubtotalTelaPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(lblSubtotalTelaPedido)
                    .addComponent(lblCódigoDescontoTelaPedido)
                    .addComponent(txtCódigoDescontoTelaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAvançarTelaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanelPedidoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAdicionarTelaPedido, btnRemoverTelaPedido});

        PanelPedidoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtProdutoTelaPedido, txtQuantidadeTelaPedido});

        jTabbedPane1.addTab("Pedido ", PanelPedido);

        tableTelaConfirmPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Valor ", "Quantidade"
            }
        ));
        jScrollPane2.setViewportView(tableTelaConfirmPedido);

        btnAvançarTelaConfirmaçãoPedido.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnAvançarTelaConfirmaçãoPedido.setText("Avançar >>");

        lblTotalPagarTelaConfirmPedido.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTotalPagarTelaConfirmPedido.setText("Total a pagar");

        btnVoltarTelaConfirmaçãoPedido.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnVoltarTelaConfirmaçãoPedido.setText("<< Voltar");

        javax.swing.GroupLayout PanelConfirmPedidoLayout = new javax.swing.GroupLayout(PanelConfirmPedido);
        PanelConfirmPedido.setLayout(PanelConfirmPedidoLayout);
        PanelConfirmPedidoLayout.setHorizontalGroup(
            PanelConfirmPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConfirmPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelConfirmPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelConfirmPedidoLayout.createSequentialGroup()
                        .addComponent(btnVoltarTelaConfirmaçãoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAvançarTelaConfirmaçãoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelConfirmPedidoLayout.createSequentialGroup()
                        .addGroup(PanelConfirmPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelConfirmPedidoLayout.createSequentialGroup()
                                .addComponent(lblTotalPagarTelaConfirmPedido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtlTotalPagarTelaConfirmPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelConfirmPedidoLayout.setVerticalGroup(
            PanelConfirmPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConfirmPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(PanelConfirmPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalPagarTelaConfirmPedido)
                    .addComponent(txtlTotalPagarTelaConfirmPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelConfirmPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAvançarTelaConfirmaçãoPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(btnVoltarTelaConfirmaçãoPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Confirmação de Pedido", PanelConfirmPedido);

        lblEscolhaFormaPagamento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblEscolhaFormaPagamento.setText("Escolha a forma de pagamento ");

        GrupoFormaPagamento.add(radioBtnDinheiro);
        radioBtnDinheiro.setText("Dinheiro");

        GrupoFormaPagamento.add(radioBtnCartãoDébito);
        radioBtnCartãoDébito.setText("Cartão Débito ");

        GrupoFormaPagamento.add(radioBtnCartãoCrédito);
        radioBtnCartãoCrédito.setText("Cartão de Crédito ");

        GrupoFormaPagamento.add(radioBtnTicketRefeição);
        radioBtnTicketRefeição.setText("Ticket Refeição ");

        lblSubtotalTelaFormaPagamento.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblSubtotalTelaFormaPagamento.setText("Subtotal ");

        lblTotalRecebidoTelaFormaPagamento.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblTotalRecebidoTelaFormaPagamento.setText("Total recebido ");

        lblTrocoTelaFormaPagamento.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblTrocoTelaFormaPagamento.setText("Troco");

        btnAvançarTelaFormaPagamento.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnAvançarTelaFormaPagamento.setText("Avançar >>");

        btnVoltarTelaFormaPagamento.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnVoltarTelaFormaPagamento.setText("<< Voltar");

        javax.swing.GroupLayout PanelFormaPagamentoLayout = new javax.swing.GroupLayout(PanelFormaPagamento);
        PanelFormaPagamento.setLayout(PanelFormaPagamentoLayout);
        PanelFormaPagamentoLayout.setHorizontalGroup(
            PanelFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFormaPagamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFormaPagamentoLayout.createSequentialGroup()
                        .addComponent(btnVoltarTelaFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAvançarTelaFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelFormaPagamentoLayout.createSequentialGroup()
                        .addGroup(PanelFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEscolhaFormaPagamento)
                            .addComponent(radioBtnDinheiro)
                            .addComponent(radioBtnCartãoDébito)
                            .addComponent(radioBtnTicketRefeição)
                            .addComponent(lblSubtotalTelaFormaPagamento)
                            .addGroup(PanelFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtSubtotalTelaFormaPagamento, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(radioBtnCartãoCrédito, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(PanelFormaPagamentoLayout.createSequentialGroup()
                                .addGroup(PanelFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PanelFormaPagamentoLayout.createSequentialGroup()
                                        .addComponent(lblTotalRecebidoTelaFormaPagamento)
                                        .addGap(85, 85, 85))
                                    .addGroup(PanelFormaPagamentoLayout.createSequentialGroup()
                                        .addComponent(txtTotalRecebidoFormaPag)
                                        .addGap(41, 41, 41)))
                                .addGroup(PanelFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTrocoTelaFormaPagamento)
                                    .addComponent(txtTrocoTelaFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 178, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelFormaPagamentoLayout.setVerticalGroup(
            PanelFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFormaPagamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEscolhaFormaPagamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBtnDinheiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBtnCartãoDébito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBtnCartãoCrédito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBtnTicketRefeição)
                .addGap(36, 36, 36)
                .addComponent(lblSubtotalTelaFormaPagamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSubtotalTelaFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalRecebidoTelaFormaPagamento)
                    .addComponent(lblTrocoTelaFormaPagamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalRecebidoFormaPag, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTrocoTelaFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(PanelFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVoltarTelaFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAvançarTelaFormaPagamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Forma de Pagamento", PanelFormaPagamento);

        lblClienteTelaFinalizarPedido.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblClienteTelaFinalizarPedido.setText("Cliente ");

        lblCodPedidoTelaFinalizarPedido.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCodPedidoTelaFinalizarPedido.setText("Cod. Pedido ");

        tableTelaFinalizarPedido.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tableTelaFinalizarPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Itens"
            }
        ));
        jScrollPane3.setViewportView(tableTelaFinalizarPedido);

        btnFinalizar.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnFinalizar.setText("Finalizar");

        btnVoltarTelaFinalizarPedido.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnVoltarTelaFinalizarPedido.setText("<< Voltar");

        javax.swing.GroupLayout PanelFinalizarPedidoLayout = new javax.swing.GroupLayout(PanelFinalizarPedido);
        PanelFinalizarPedido.setLayout(PanelFinalizarPedidoLayout);
        PanelFinalizarPedidoLayout.setHorizontalGroup(
            PanelFinalizarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFinalizarPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelFinalizarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFinalizarPedidoLayout.createSequentialGroup()
                        .addGroup(PanelFinalizarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodPedidoTelaFinalizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblClienteTelaFinalizarPedido)
                            .addComponent(lblCodPedidoTelaFinalizarPedido)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtClienteTelaFinalizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(PanelFinalizarPedidoLayout.createSequentialGroup()
                        .addComponent(btnVoltarTelaFinalizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFinalizar)))
                .addContainerGap())
        );

        PanelFinalizarPedidoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtClienteTelaFinalizarPedido, txtCodPedidoTelaFinalizarPedido});

        PanelFinalizarPedidoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnFinalizar, btnVoltarTelaFinalizarPedido});

        PanelFinalizarPedidoLayout.setVerticalGroup(
            PanelFinalizarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFinalizarPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClienteTelaFinalizarPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClienteTelaFinalizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCodPedidoTelaFinalizarPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodPedidoTelaFinalizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(PanelFinalizarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinalizar)
                    .addComponent(btnVoltarTelaFinalizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PanelFinalizarPedidoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtClienteTelaFinalizarPedido, txtCodPedidoTelaFinalizarPedido});

        PanelFinalizarPedidoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnFinalizar, btnVoltarTelaFinalizarPedido});

        jTabbedPane1.addTab("Finalizar Pedido", PanelFinalizarPedido);

        lblÁreaVendas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblÁreaVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastroProdutos.png"))); // NOI18N
        lblÁreaVendas.setText("Área de Vendas ");

        btnMenu.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnMenu.setText("Menu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblÁreaVendas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblÁreaVendas)
                    .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoverTelaPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverTelaPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoverTelaPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoFormaPagamento;
    private javax.swing.JPanel PanelConfirmPedido;
    private javax.swing.JPanel PanelFinalizarPedido;
    private javax.swing.JPanel PanelFormaPagamento;
    private javax.swing.JPanel PanelPedido;
    private javax.swing.JButton btnAdicionarTelaPedido;
    private javax.swing.JButton btnAvançarTelaConfirmaçãoPedido;
    private javax.swing.JButton btnAvançarTelaFormaPagamento;
    private javax.swing.JButton btnAvançarTelaPedido;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnRemoverTelaPedido;
    private javax.swing.JButton btnVoltarTelaConfirmaçãoPedido;
    private javax.swing.JButton btnVoltarTelaFinalizarPedido;
    private javax.swing.JButton btnVoltarTelaFormaPagamento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblClienteTelaFinalizarPedido;
    private javax.swing.JLabel lblCodPedidoTelaFinalizarPedido;
    private javax.swing.JLabel lblCódigoDescontoTelaPedido;
    private javax.swing.JLabel lblCódigoTelaPedido;
    private javax.swing.JLabel lblEscolhaFormaPagamento;
    private javax.swing.JLabel lblProdutoTelaPedido;
    private javax.swing.JLabel lblQuantidadeTelaPedido;
    private javax.swing.JLabel lblSubtotalTelaFormaPagamento;
    private javax.swing.JLabel lblSubtotalTelaPedido;
    private javax.swing.JLabel lblTotalPagarTelaConfirmPedido;
    private javax.swing.JLabel lblTotalRecebidoTelaFormaPagamento;
    private javax.swing.JLabel lblTrocoTelaFormaPagamento;
    private javax.swing.JLabel lblÁreaVendas;
    private javax.swing.JRadioButton radioBtnCartãoCrédito;
    private javax.swing.JRadioButton radioBtnCartãoDébito;
    private javax.swing.JRadioButton radioBtnDinheiro;
    private javax.swing.JRadioButton radioBtnTicketRefeição;
    private javax.swing.JTable tableTelaConfirmPedido;
    private javax.swing.JTable tableTelaFinalizarPedido;
    private javax.swing.JTable tableTelaPedido;
    private javax.swing.JTextField txtClienteTelaFinalizarPedido;
    private javax.swing.JTextField txtCodPedidoTelaFinalizarPedido;
    private javax.swing.JTextField txtCódigoDescontoTelaPedido;
    private javax.swing.JTextField txtCódigoTelaPedido;
    private javax.swing.JTextField txtProdutoTelaPedido;
    private javax.swing.JTextField txtQuantidadeTelaPedido;
    private javax.swing.JTextField txtSubtotalTelaFormaPagamento;
    private javax.swing.JTextField txtSubtotalTelaPedido;
    private javax.swing.JTextField txtTotalRecebidoFormaPag;
    private javax.swing.JTextField txtTrocoTelaFormaPagamento;
    private javax.swing.JTextField txtlTotalPagarTelaConfirmPedido;
    // End of variables declaration//GEN-END:variables
}
